export const POST_REDIRECTS: Record<string, string> = {
  // 할로윈 더 게임 (15건)
  'halloween-the-game-civilian-characters-guide': '/posts/halloween-the-game-civilian-guide/',
  'halloween-the-game-civilian-stats-guide': '/posts/halloween-the-game-civilian-guide/',
  'halloween-the-game-michael-abilities-guide': '/posts/halloween-the-game-michael-myers-guide/',
  'halloween-the-game-shape-jump-guide': '/posts/halloween-the-game-michael-myers-guide/',
  'halloween-the-game-stalking-guide': '/posts/halloween-the-game-michael-myers-guide/',
  'halloween-the-game-haddonfield-heights-guide': '/posts/halloween-the-game-maps-guide/',
  'halloween-the-game-town-center-guide': '/posts/halloween-the-game-maps-guide/',
  'halloween-the-game-orange-grove-guide': '/posts/halloween-the-game-maps-guide/',
  'halloween-the-game-east-haddonfield-guide': '/posts/halloween-the-game-maps-guide/',
  'halloween-the-game-arrest-guide': '/posts/halloween-the-game-residents-police-guide/',
  'halloween-the-game-after-death-guide': '/posts/halloween-the-game-residents-police-guide/',
  'halloween-the-game-story-challenges-guide': '/posts/halloween-the-game-story-mode-guide/',
  'halloween-the-game-challenges-guide': '/posts/halloween-the-game-leveling-guide/',
  'halloween-the-game-perk-deck-guide': '/posts/halloween-the-game-leveling-guide/',
  'halloween-the-game-loot-guide': '/posts/halloween-the-game-escape-guide/',

  // 몬스터헌터 와일즈 (5건)
  'monster-hunter-wilds-faq-guide': '/posts/monster-hunter-wilds-beginner-guide/',
  'monster-hunter-wilds-hunter-rank-guide': '/posts/monster-hunter-wilds-beginner-guide/',
  'monster-hunter-wilds-weapon-crafting-guide': '/posts/monster-hunter-wilds-armor-progression-guide/',
  'monster-hunter-wilds-food-guide': '/posts/monster-hunter-wilds-prep-and-items-guide/',
  'monster-hunter-wilds-capture-guide': '/posts/monster-hunter-wilds-monster-list-guide/',

  // 봄바나나 (9건)
  'bombanana-role-choice': '/posts/bombanana-beginner-guide/',
  'bombanana-mute-monkey': '/posts/bombanana-beginner-guide/',
  'bombanana-deaf-monkey': '/posts/bombanana-beginner-guide/',
  'bombanana-blind-monkey': '/posts/bombanana-beginner-guide/',
  'bombanana-communication-guide': '/posts/bombanana-beginner-guide/',
  'bombanana-puzzle-modules': '/posts/bombanana-campaign-guide/',
  'bombanana-environment-hazards': '/posts/bombanana-campaign-guide/',
  'bombanana-endless-mode': '/posts/bombanana-custom-mode/',
  'bombanana-voice-chat-fix': '/posts/bombanana-crash-patch/',

  // 발하임 (3건)
  'valheim-armor-tier-guide': '/posts/valheim-weapon-tier-list-guide/',
  'valheim-farming-taming-guide': '/posts/valheim-food-guide/',
  'valheim-1-0-deep-north-guide': '/posts/valheim-deep-north-in-depth-guide/',

  // 더 블러드 오브 던워커 (7건)
  'dawnwalker-quest-order-guide': '/posts/dawnwalker-beginner-guide/',
  'dawnwalker-time-guide': '/posts/dawnwalker-beginner-guide/',
  'dawnwalker-gear-guide': '/posts/dawnwalker-combat-guide/',
  'dawnwalker-skill-build-guide': '/posts/dawnwalker-combat-guide/',
  'dawnwalker-ending-guide': '/posts/dawnwalker-choices-guide/',
  'dawnwalker-romance-guide': '/posts/dawnwalker-choices-guide/',
  'dawnwalker-trophy-guide': '/posts/dawnwalker-map-collectibles-guide/',

  // 뮤제닉스 (4건)
  'mewgenics-battle-tactics-guide': '/posts/mewgenics-guide/',
  'mewgenics-class-guide': '/posts/mewgenics-guide/',
  'mewgenics-mutation-guide': '/posts/mewgenics-breeding-guide/',
  'mewgenics-donation-guide': '/posts/mewgenics-house-guide/',

  // 귀무자 웨이 오브 더 소드 (7건)
  'onimusha-combat-guide': '/posts/onimusha-beginner-guide/',
  'onimusha-difficulty-guide': '/posts/onimusha-beginner-guide/',
  'onimusha-skill-tree-guide': '/posts/onimusha-upgrade-guide/',
  'onimusha-soul-farming-guide': '/posts/onimusha-upgrade-guide/',
  'onimusha-charms-guide': '/posts/onimusha-upgrade-guide/',
  'onimusha-secrets-hidden-treasures-guide': '/posts/onimusha-collectibles-guide/',
  'onimusha-spirit-mirror-locations-guide': '/posts/onimusha-collectibles-guide/',

  // 프라그마타 (20건)
  'pragmata-hacking-basics': '/posts/pragmata-beginner-guide/',
  'pragmata-overdrive-guide': '/posts/pragmata-beginner-guide/',
  'pragmata-shelter-escape-hatch': '/posts/pragmata-beginner-guide/',
  'pragmata-attack-units': '/posts/pragmata-weapon-system/',
  'pragmata-defense-units': '/posts/pragmata-weapon-system/',
  'pragmata-tactical-units': '/posts/pragmata-weapon-system/',
  'pragmata-primary-units': '/posts/pragmata-weapon-system/',
  'pragmata-unit-printer': '/posts/pragmata-best-loadout/',
  'pragmata-firmware-updater': '/posts/pragmata-upgrade-priority/',
  'pragmata-hacking-nodes': '/posts/pragmata-upgrade-priority/',
  'pragmata-creator-boss': '/posts/pragmata-sector-guard/',
  'pragmata-garden-keeper': '/posts/pragmata-sector-guard/',
  'pragmata-lunadigger': '/posts/pragmata-sector-guard/',
  'pragmata-final-boss': '/posts/pragmata-sector-guard/',
  'pragmata-lunatic-mode': '/posts/pragmata-new-game-plus/',
  'pragmata-red-zone-pure-lunum': '/posts/pragmata-new-game-plus/',
  'pragmata-unknown-signal': '/posts/pragmata-new-game-plus/',
  'pragmata-collectibles-100': '/posts/pragmata-achievements-guide/',
  'pragmata-cabin-stamp-club': '/posts/pragmata-achievements-guide/',
  'pragmata-fps-optimization': '/posts/pragmata-pc-requirements/',

  // 모탈 셸 2 (23건)
  'mortal-shell-2-combat-guide': '/posts/mortal-shell-2-beginner-guide/',
  'mortal-shell-2-progression-route': '/posts/mortal-shell-2-beginner-guide/',
  'mortal-shell-2-beacons': '/posts/mortal-shell-2-beginner-guide/',
  'mortal-shell-2-dungeons': '/posts/mortal-shell-2-beginner-guide/',
  'mortal-shell-2-eredrim-guide': '/posts/mortal-shell-2-all-shells/',
  'mortal-shell-2-genessa-guide': '/posts/mortal-shell-2-all-shells/',
  'mortal-shell-2-late-shells': '/posts/mortal-shell-2-all-shells/',
  'mortal-shell-2-proxima-guide': '/posts/mortal-shell-2-all-shells/',
  'mortal-shell-2-tiel-guide': '/posts/mortal-shell-2-all-shells/',
  'mortal-shell-2-sidearms': '/posts/mortal-shell-2-weapons/',
  'mortal-shell-2-healing': '/posts/mortal-shell-2-tarforge/',
  'mortal-shell-2-tarstones': '/posts/mortal-shell-2-tarforge/',
  'mortal-shell-2-tar-golem': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-droeg': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-hexapod': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-lost-child': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-magdalena': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-malborn': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-monolith': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-nameless-captive': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-orrem': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-sir-isaac': '/posts/mortal-shell-2-zmey/',
  'mortal-shell-2-collectibles': '/posts/mortal-shell-2-achievements-ngplus/',

  // 랜덤 다이스 2 (5건)
  'random-dice-2-battle-tips-guide': '/posts/random-dice-2-beginner-guide/',
  'random-dice-2-electric-deck-guide': '/posts/random-dice-2-deck-tier-guide/',
  'random-dice-2-gear-deck-guide': '/posts/random-dice-2-deck-tier-guide/',
  'random-dice-2-predation-deck-guide': '/posts/random-dice-2-deck-tier-guide/',
  'random-dice-2-resonance-deck-guide': '/posts/random-dice-2-deck-tier-guide/',

  // 낚시 방법 (17건)
  'how-to-fish-fishing-basics': '/posts/how-to-fish-beginner-guide/',
  'how-to-fish-rods-lures': '/posts/how-to-fish-beginner-guide/',
  'how-to-fish-boat-radar': '/posts/how-to-fish-beginner-guide/',
  'how-to-fish-quest-items': '/posts/how-to-fish-island-progression/',
  'how-to-fish-rocks-tuna-albatross': '/posts/how-to-fish-island-progression/',
  'how-to-fish-desert-pufferfish': '/posts/how-to-fish-island-progression/',
  'how-to-fish-forest-piranha': '/posts/how-to-fish-island-progression/',
  'how-to-fish-grill-food': '/posts/how-to-fish-money-trickshots/',
  'how-to-fish-drip-variants': '/posts/how-to-fish-money-trickshots/',
  'how-to-fish-fishipedia': '/posts/how-to-fish-money-trickshots/',
  'how-to-fish-bean-speedrun': '/posts/how-to-fish-achievements/',
  'how-to-fish-handyman': '/posts/how-to-fish-achievements/',
  'how-to-fish-volcano-final-boss': '/posts/how-to-fish-lighthouse-spider-crab/',
  'how-to-fish-weapon-guide': '/posts/how-to-fish-lighthouse-spider-crab/',
  'how-to-fish-solo-guide': '/posts/how-to-fish-multiplayer/',
  'how-to-fish-steam-deck-cloud': '/posts/how-to-fish-pc-issues/',
  'how-to-fish-gambling': '/posts/how-to-fish-reel-of-fortune/',
};
