locale: "en-US"
title: "Danmaek"
name: "Proteinbeer"
description: "Practical reviews of Korean snacks, instant noodles, and drinks."
url: "https://danmaek.com"
baseurl: ""
repository: "proteinbeer/danmaek"
google_site_verification: "A4nFf24Qp22HoqhIdaDgC0vwzYcfEnY0NwvZSYud0hg"
