remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

locale: "ko-KR"
title: "단맥"
name: "Proteinbeer"
description: "한국 & 영미권 이야기"
url: "https://danmaek.com"
baseurl: ""
repository: "proteinbeer/danmaek"
masthead_title: " "

twitter:
  username: &twitter "proteinbeer"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

include:
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

compress_html:
  clippings: all
  ignore:
    envs: development
